version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go-v2/*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "chore"