version: "2"
linters:
  enable:
    - gosec
    - loggercheck
    - misspell
    - revive
    - sloglint
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    gosec:
      excludes:
        - G115  # Flags for potentially-unsafe casting of ints
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: provider/providers.go  # TLS verification is skipped when provider.Insecure() == true
        text: InsecureSkipVerify
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
